//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeTable.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DateTimeTable.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Masoud Rahmani
        ///-- Create date: 2019
        ///-- Description:	Returns Corrosponding Gregorian Date for a Shamsi date
        ///--				Input: shamsi date string year/month/day and Returns: gregorain (miladi) DATE
        ///-- =============================================
        ///CREATE FUNCTION GetMiladi
        ///(
        ///	@inDate CHAR(10)
        ///)
        ///RETURNS DATE
        ///AS
        ///BEGIN
        ///	DECLARE	@result DATE;
        ///	
        ///	SELECT	@result = d.GregorianDate
        ///	FROM	dbo.DimDate d
        ///	WHERE	d.PersianStr = @inDate;
        ///
        ///	RETURN @re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMiladi {
            get {
                return ResourceManager.GetString("GetMiladi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Masoud Rahmani
        ///-- Create date: 2019
        ///-- Description:	Returns Corrosponding Shamsi Date for given date
        ///--				Input: Gregorian Date and Returns: Shamsi nvarchar(10) Date
        ///-- =============================================
        ///CREATE FUNCTION GetShamsi
        ///(
        ///	@inDate DATETIME
        ///)
        ///RETURNS NVARCHAR(10)
        ///AS
        ///BEGIN
        ///	DECLARE @result NVARCHAR(10);
        ///	
        ///	SELECT @result=d.PersianStr
        ///	FROM dbo.DimDate d
        ///	WHERE GregorianDate = CONVERT(DATE, @inDate);
        ///
        ///	RETURN  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetShamsi {
            get {
                return ResourceManager.GetString("GetShamsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DimDate](
        ///	[DateKey] [INT] NOT NULL,
        ///	[GregorianDate] [DATE] NULL,
        ///	[GregorianYearInt] [SMALLINT] NULL,
        ///	[GregorianMonthNo] [TINYINT] NULL,
        ///	[GregorianDayInMonth] [TINYINT] NULL,
        ///	[GregorianMonthDayInt] [SMALLINT] NULL,
        ///	[GregorianDayOfWeekInt] [TINYINT] NULL,
        ///	[GregorianMonthName] [NVARCHAR](20) NULL,
        ///	[GregorianStr] [CHAR](10) NULL,
        ///	[GregorianYearMonthInt] [INT] NULL,
        ///	[GregorianYearMonthStr] [CHAR](7) NULL,
        ///	[GregorianDayOfWeekName] [NVARCHAR](20) NULL,
        ///	[GrgorianWeekOfY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
    }
}
