name: .NET Core Desktop
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest  
    env:
      Solution_Name: DateTimeTable.sln  
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish DateTimeTable.csproj -c Release -o DateTime
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DateTime
        path: /
        if-no-files-found: error
